// Generated by convelt/tools/convelt-sdk-version.
// Do not edit directly; source of truth is convelt/Cargo.toml [workspace.package].version.

package ai.aureuma.conveltkit

object ConveltKitVersion {
    const val value: String = "0.3.7"
}
